"""
Information Integration module based on Integrated Information Theory (IIT)

NOTE: This implements approximations of IIT phi, not exact calculations.
True IIT phi computation is computationally infeasible for large systems
(super-exponential complexity). This module uses correlation-based proxies
and partition sampling to estimate integrated information.

References:
- Tononi et al. (2016) "Integrated Information Theory"
- Oizumi et al. (2014) "From the Phenomenology to the Mechanisms of Consciousness"
"""

import torch
import numpy as np
from typing import List, Dict, Tuple
from itertools import combinations
import torch.nn.functional as F


class InformationIntegrator:
    """
    Calculates Integrated Information (Φ) approximations based on IIT principles.

    This is a computationally tractable approximation using:
    - Correlation-based mutual information estimates
    - Partition sampling (not exhaustive search)
    - Layer-wise state analysis

    The resulting phi values are proxies for consciousness-like integration,
    not rigorous IIT phi calculations (which are infeasible for large systems).
    """
    
    def __init__(self):
        self.phi_history = []
        self.partition_cache = {}
        
    def calculate_phi(self, states: List[torch.Tensor]) -> float:
        """
        Calculate Φ (integrated information) for a list of layer states.
        
        This is a simplified version that captures the essence of IIT:
        - Measures how much information is generated by the whole beyond its parts
        - Higher Φ indicates more integrated, conscious-like processing
        """
        if not states or len(states) < 2:
            return 0.0
        
        # Convert states to numpy for easier manipulation
        state_arrays = [s.detach().cpu().numpy() if isinstance(s, torch.Tensor) else s 
                       for s in states]
        
        # Calculate total system information
        system_info = self._calculate_system_information(state_arrays)
        
        # Find the partition that minimizes information loss
        min_partition_info = self._find_minimum_partition(state_arrays)
        
        # Φ is the difference between integrated and partitioned information
        phi = system_info - min_partition_info
        phi = max(0.0, phi)  # Φ cannot be negative
        
        self.phi_history.append(phi)
        
        return phi
    
    def _calculate_system_information(self, states: List[np.ndarray]) -> float:
        """
        Calculate total information in the system using mutual information
        between consecutive layers.
        """
        total_info = 0.0
        
        for i in range(len(states) - 1):
            # Calculate mutual information between consecutive layers
            mi = self._mutual_information(states[i], states[i + 1])
            total_info += mi
        
        return total_info
    
    def _mutual_information(self, x: np.ndarray, y: np.ndarray) -> float:
        """
        Estimate mutual information between two layer states.
        Using a correlation-based approximation for efficiency.
        """
        # Flatten if needed
        x_flat = x.flatten()
        y_flat = y.flatten()
        
        # Normalize
        x_norm = (x_flat - x_flat.mean()) / (x_flat.std() + 1e-8)
        y_norm = (y_flat - y_flat.mean()) / (y_flat.std() + 1e-8)
        
        # Correlation as proxy for mutual information
        correlation = np.abs(np.corrcoef(x_norm, y_norm)[0, 1])
        
        # Convert to information-theoretic measure
        # Using -log(1-r²) as approximation
        if correlation < 0.999:
            mi_approx = -np.log(1 - correlation**2)
        else:
            mi_approx = 10.0  # Cap for numerical stability
        
        return mi_approx
    
    def _find_minimum_partition(self, states: List[np.ndarray]) -> float:
        """
        Find the partition of the system that yields minimum integrated information.
        This represents the "weakest link" in the system's integration.
        """
        n_layers = len(states)
        if n_layers <= 2:
            return 0.0
        
        min_info = float('inf')
        
        # Try different bipartitions
        for partition_size in range(1, n_layers // 2 + 1):
            for partition_indices in combinations(range(n_layers), partition_size):
                # Calculate information for this partition
                partition_info = self._calculate_partition_information(
                    states, partition_indices
                )
                min_info = min(min_info, partition_info)
        
        return min_info
    
    def _calculate_partition_information(
        self, states: List[np.ndarray], partition_indices: Tuple[int, ...]
    ) -> float:
        """
        Calculate information when system is partitioned at given indices.
        """
        partition_a_indices = list(partition_indices)
        partition_b_indices = [i for i in range(len(states)) if i not in partition_indices]
        
        if not partition_a_indices or not partition_b_indices:
            return 0.0
        
        # Information within each partition
        info_a = self._calculate_within_partition_info(states, partition_a_indices)
        info_b = self._calculate_within_partition_info(states, partition_b_indices)
        
        # Information between partitions (should be minimal for a good partition)
        info_between = self._calculate_between_partition_info(
            states, partition_a_indices, partition_b_indices
        )
        
        return info_a + info_b + 0.5 * info_between
    
    def _calculate_within_partition_info(
        self, states: List[np.ndarray], indices: List[int]
    ) -> float:
        """Calculate information within a partition."""
        if len(indices) < 2:
            return 0.0
        
        total_info = 0.0
        for i in range(len(indices) - 1):
            idx1, idx2 = indices[i], indices[i + 1]
            if abs(idx2 - idx1) == 1:  # Adjacent layers
                total_info += self._mutual_information(states[idx1], states[idx2])
        
        return total_info
    
    def _calculate_between_partition_info(
        self, states: List[np.ndarray], 
        indices_a: List[int], 
        indices_b: List[int]
    ) -> float:
        """Calculate information between two partitions."""
        # Find boundary connections
        boundary_info = 0.0
        
        for idx_a in indices_a:
            for idx_b in indices_b:
                if abs(idx_a - idx_b) == 1:  # Adjacent across partition
                    boundary_info += self._mutual_information(
                        states[idx_a], states[idx_b]
                    )
        
        return boundary_info
    
    def get_integration_metrics(self) -> Dict[str, float]:
        """Get various metrics related to information integration."""
        if not self.phi_history:
            return {
                "current_phi": 0.0,
                "average_phi": 0.0,
                "max_phi": 0.0,
                "phi_trend": 0.0,
            }
        
        current_phi = self.phi_history[-1]
        average_phi = np.mean(self.phi_history)
        max_phi = np.max(self.phi_history)
        
        # Calculate trend (positive = increasing integration)
        if len(self.phi_history) > 5:
            recent = self.phi_history[-5:]
            older = self.phi_history[-10:-5] if len(self.phi_history) > 10 else self.phi_history[:5]
            phi_trend = np.mean(recent) - np.mean(older)
        else:
            phi_trend = 0.0
        
        return {
            "current_phi": current_phi,
            "average_phi": average_phi,
            "max_phi": max_phi,
            "phi_trend": phi_trend,
        }
    
    def calculate_consciousness_indicators(
        self, states: List[torch.Tensor]
    ) -> Dict[str, float]:
        """
        Calculate various indicators of consciousness-like properties.
        """
        phi = self.calculate_phi(states)
        
        # Differentiation: How distinct are the states?
        differentiation = self._calculate_differentiation(states)
        
        # Integration: How unified is the processing?
        integration = self._calculate_integration(states)
        
        # Complexity: Balance between differentiation and integration
        complexity = differentiation * integration
        
        return {
            "phi": phi,
            "differentiation": differentiation,
            "integration": integration,
            "complexity": complexity,
        }
    
    def _calculate_differentiation(self, states: List[torch.Tensor]) -> float:
        """
        Measure how differentiated/diverse the states are.
        High differentiation suggests rich, varied processing.
        """
        if len(states) < 2:
            return 0.0
        
        # Calculate variance across states
        state_arrays = [s.detach().cpu().numpy().flatten() for s in states]
        
        # Variance across different layers
        cross_layer_variance = np.var([s.mean() for s in state_arrays])
        
        # Variance within each layer
        within_layer_variance = np.mean([s.var() for s in state_arrays])
        
        differentiation = (cross_layer_variance + within_layer_variance) / 2
        
        return float(differentiation)
    
    def _calculate_integration(self, states: List[torch.Tensor]) -> float:
        """
        Measure how integrated/unified the states are.
        High integration suggests coherent, unified processing.
        """
        if len(states) < 2:
            return 0.0
        
        # Calculate average correlation between consecutive states
        correlations = []
        
        for i in range(len(states) - 1):
            state1 = states[i].detach().cpu().numpy().flatten()
            state2 = states[i + 1].detach().cpu().numpy().flatten()
            
            if len(state1) == len(state2):
                corr = np.corrcoef(state1, state2)[0, 1]
                correlations.append(abs(corr))
        
        integration = np.mean(correlations) if correlations else 0.0
        
        return float(integration)